query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 63/269 (23%), Positives = 113/269 (42%), Gaps = 36/269 (13%)

Query: 1518 FVTQQAFDIVIMMLICLNMVTMMVET--DTQSKQMENILYWINLVFVIFFTCECVLKMFA 1575
            FV    F   I  ++ +N + ++VET  D +    +        VF   +  E  LK++ 
Sbjct: 426  FVRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYT 485

Query: 1576 LR-HYYFTIGWNIFDFVVVILSIVG---MFLADIIEKYFVSPTLFRVIRLARIGRILRLI 1631
                 Y+  G N FDF+V  + ++G    F+      +F +    R + LAR+ R++RL+
Sbjct: 486  YGFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLL 545

Query: 1632 KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIFSIFGMSNFA---------YVKHEAGI 1682
               +  R  +   +  +P+L      +F V+ I+   G+  F            + E   
Sbjct: 546  MNVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETELAE 605

Query: 1683 DD--MFNFETFGNSMICLFQITTSAGWDGLLLPILNRPPDCSLDKEHPGSGFKGDCGNPS 1740
            DD  +FNF  + N M+ LF +     W   +                    +K D     
Sbjct: 606  DDYLLFNFNDYPNGMVTLFNLLVMGNWQVWM------------------ESYK-DLTGTW 646

Query: 1741 VGIFFFVSYIIISFLIVVNMYIAIILENF 1769
              I +FVS+ +I+ L+++N+ +A +LE F
Sbjct: 647  WSITYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 62.3 bits (150), Expect = 3e-09,   Method: Composition-based stats.
 Identities = 73/325 (22%), Positives = 131/325 (40%), Gaps = 47/325 (14%)

Query: 1200 FETFIIFMILLSSGALAFEDIYIEQRKTIRTILEYADKVFTYIFILEMLLKWTAYGFVKF 1259
            F   I F+++++  A+  E     +  + +   + A+ VF +I++LEM LK   YGF  +
Sbjct: 432  FGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTYGFENY 491

Query: 1260 FTNAWCWLDFLIVAVSLVSLIANALG------YSELGAIKSLRTLRALRPLRALSRFEGM 1313
            +       DFL+  V ++   A  +       +S    I+ L   R LR +R L   +  
Sbjct: 492  WREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNVQRY 551

Query: 1314 RVVVNALVGAIPSIMNVLLVCLIFWLIFSIMGVNLFAGKYHYCFNETSEIRFEIEDVNNK 1373
            R  +   +  IPS+M  L        I+  +GV +F G               + +  NK
Sbjct: 552  RAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGG---------------LVNAGNK 596

Query: 1374 TECEKLMEGNNTEIRWKNVKINFDNVGAGYLALLQVATFKGWMDIMYAAVDSRKPDEQPK 1433
                KL E    E  +  +  NF++   G + L  +     W   M +  D         
Sbjct: 597  ----KLFETELAEDDY--LLFNFNDYPNGMVTLFNLLVMGNWQVWMESYKD--------- 641

Query: 1434 YEDNIYMYIYFVIFIIFGSFFTLNLFIGVIIDNFN-----QQKKKFGGQDIFMTEEQKKY 1488
                 +   YFV F +      LNL +  +++ F      ++++K  GQD   ++E++  
Sbjct: 642  LTGTWWSITYFVSFYVITILLLLNLVVAFVLEAFFTELDLEEEEKCQGQD---SQEKR-- 696

Query: 1489 YNAMKKLGSKKPQKPIPRPLNKIQG 1513
             N  +  GSK   + +   L+ + G
Sbjct: 697  -NRRRSAGSKSRSQRVDTLLHHMLG 720



 Score = 46.2 bits (108), Expect = 3e-04,   Method: Composition-based stats.
 Identities = 41/193 (21%), Positives = 79/193 (40%), Gaps = 34/193 (17%)

Query: 1580 YFTIGWNIFDFVVVILSIVGMFLADIIEKYFVSPTLFRVI--RLARIGRILRLIKGAKGI 1637
            ++T   N    +V +  +V +F+  +++  ++SP  F  +  R+A   R++  I   + +
Sbjct: 147  FWTSRLN----LVKVACVVILFVDVLVDFLYLSPLAFDFLPFRIAPYVRVIIFILSIREL 202

Query: 1638 RTLLFALMMSLPALFNIGLLLFLVMFIFSIFGMSNFAYVKHEAGIDDMFNFETFGNSMIC 1697
            R  L  L   L    NI  L  L +   S       A+V  E     +  F ++G ++  
Sbjct: 203  RDTLVLLSGMLGTYLNILALWMLFLLFASWI-----AFVMFEDTQQGLTVFTSYGATLYQ 257

Query: 1698 LFQI-TTSAGWDGLLLPILNRPPDCSLDKEHPGSGFKGDCGNPSVGIFFFVSYIIISFLI 1756
            +F + TTS   D  +                    +K    +      FFV Y++I    
Sbjct: 258  MFILFTTSNNPDVWIP------------------AYK----SSRWSSVFFVLYVLIGVYF 295

Query: 1757 VVNMYIAIILENF 1769
            V N+ +A++ ++F
Sbjct: 296  VTNLILAVVYDSF 308



 Score = 44.6 bits (104), Expect = 7e-04,   Method: Composition-based stats.
 Identities = 64/270 (23%), Positives = 117/270 (43%), Gaps = 36/270 (13%)

Query: 738 YWIKLKEIVNLIVMDPFVDLAITICIVLNTLFMAMEHHPMTPQFEHVLA-----VGNLVF 792
           Y   L + +   V  P    AI+  +++N + + +E    T   E   A     V   VF
Sbjct: 415 YHSALSQQLRAFVRSPNFGYAISFILIINFIAVVVE---TTLDIEESSAQKPWQVAEFVF 471

Query: 793 TGIFTAEMFLKLIAMDPYYYFQEGWNIFDGFIVSLSLMELSLAD---------------V 837
             I+  EM LK+       Y++EG N FD F+V+  ++    A                +
Sbjct: 472 GWIYVLEMALKIYTYGFENYWREGANRFD-FLVTWVIVIGETATFITPDENTFFSNGEWI 530

Query: 838 EGLSVLRSFRLLRVFKLAKSWPT-LNMLIKIIGNSVGALGNLTLVLAIIVFIFAVVGMQL 896
             L + R  RL+R+    + +   +   I +I + +  LG +  VL     I+  +G+Q+
Sbjct: 531 RYLLLARMLRLIRLLMNVQRYRAFIATFITLIPSLMPYLGTIFCVLC----IYCSIGVQV 586

Query: 897 FG-----KSYKECVCKINQDCELPRWHMHDFFHSFLIVFRVLC-GEWIETMWDCMEVAGQ 950
           FG      + K    ++ +D  L  ++ +D+ +  + +F +L  G W   M    ++ G 
Sbjct: 587 FGGLVNAGNKKLFETELAEDDYL-LFNFNDYPNGMVTLFNLLVMGNWQVWMESYKDLTGT 645

Query: 951 AMCLIVFMMVMVIGNLVVLNLFLALLLSSF 980
              +  F+   VI  L++LNL +A +L +F
Sbjct: 646 WWSITYFVSFYVITILLLLNLVVAFVLEAF 675


