query
>KCNS2_MOUSE#plasma membrane#voltage-gated potassium channel complex
 Identities = 45/161 (27%), Positives = 76/161 (47%), Gaps = 15/161 (9%)

Query: 1360 MILICLNMVTMMVETDNQSQLKVDILYNINMIF-IIIFTGECVLKMLALRQY--YFTVGW 1416
            +I +CLN +      D+Q     D  + I   F I  FT E V +      +  +F    
Sbjct: 201  IITMCLNSLPDFQIPDSQGNPGEDPRFEIVEHFGIAWFTFELVARFAVAPDFLKFFKNAL 260

Query: 1417 NIFDFVVVILSIVGLALSDLIQKYFVSPTLF------RVIRLARIGRVLRLIRGAKGIRT 1470
            N+ D + ++   + L ++ +++    SPTL       +V+RL RI R+L+L R + G+R+
Sbjct: 261  NLIDLMSIVPFYITLVVNLVVES---SPTLANLGRVAQVLRLMRIFRILKLARHSTGLRS 317

Query: 1471 LLFALMMSLPALFNIGLLLFLVMFIYSIFGMSNFAYVKKES 1511
            L   L  S      +GLLL  +    SIF +  +   K+E+
Sbjct: 318  LGATLKYSYK---EVGLLLLYLSVGISIFSVVAYTIEKEEN 355


