query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 62/266 (23%), Positives = 113/266 (42%), Gaps = 40/266 (15%)

Query: 1478 FDITIMVLICLNMITMMVETD-DQSEEKTKILGKINQF-FVAVFTGECVMKMFALRQYYF 1535
            F   I  ++ +N I ++VET  D  E   +   ++ +F F  ++  E  +K++    Y F
Sbjct: 432  FGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYT---YGF 488

Query: 1536 TNGW----NVFDFIVVVLSIASLIFSAILKSLQSYFSP-TLFRVIRLARIGRILRLIRAA 1590
             N W    N FDF+V  + +     + I     ++FS     R + LAR+ R++RL+   
Sbjct: 489  ENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNV 548

Query: 1591 KGIRTLLFALMMSLPALFNIGLLLFLVMFIYSIFGMSSFPHV---------RWEAGIDD- 1640
            +  R  +   +  +P+L      +F V+ IY   G+  F  +           E   DD 
Sbjct: 549  QRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETELAEDDY 608

Query: 1641 -MFNFQTFANSMLCLFQITTSAGWDGLLSPILNTGPPYCDPNLPNSNGTRGDCGSPAVGI 1699
             +FNF  + N M+ LF +     W   +                    +  D       I
Sbjct: 609  LLFNFNDYPNGMVTLFNLLVMGNWQVWME-------------------SYKDLTGTWWSI 649

Query: 1700 IFFTTYIIISFLIMVNMYIAVILENF 1725
             +F ++ +I+ L+++N+ +A +LE F
Sbjct: 650  TYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 63.1 bits (152), Expect = 2e-09,   Method: Composition-based stats.
 Identities = 72/325 (22%), Positives = 130/325 (40%), Gaps = 47/325 (14%)

Query: 1154 FESFIIFMILLSSGSLAFEDYYLDQKPTVKALLEYTDRVFTFIFVFEMLLKWVAYGFKKY 1213
            F   I F+++++  ++  E     ++ + +   +  + VF +I+V EM LK   YGF+ Y
Sbjct: 432  FGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTYGFENY 491

Query: 1214 FTNAWCWLDFLIVNISLISLTAKILE------YSEVAPIKALRTLRALRPLRALSRFEGM 1267
            +       DFL+  + +I  TA  +       +S    I+ L   R LR +R L   +  
Sbjct: 492  WREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNVQRY 551

Query: 1268 RVVVDALVGAIPSIMNVLLVCLIFWLIFSIMGVNLFAGKFWRCINYTDGEFSLVPLSIVN 1327
            R  +   +  IPS+M  L        I+  +GV +F G                 L    
Sbjct: 552  RAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGG-----------------LVNAG 594

Query: 1328 NKSDCKIQNSTGSFFWVNVKVNFDNVAMGYLALLQVATFKGWMDIMYAAVDSREVNMQPK 1387
            NK   + + +   +       NF++   G + L  +     W   M +  D     +   
Sbjct: 595  NKKLFETELAEDDYLL----FNFNDYPNGMVTLFNLLVMGNWQVWMESYKD-----LTGT 645

Query: 1388 WEDNVYMYLYFVIFIIFGGFFTLNLFVGVIIDNFN-----QQKKKLGGQDIFMTEEQKKY 1442
            W    +   YFV F +      LNL V  +++ F      ++++K  GQD   ++E++  
Sbjct: 646  W----WSITYFVSFYVITILLLLNLVVAFVLEAFFTELDLEEEEKCQGQD---SQEKR-- 696

Query: 1443 YNAMKKLGSKKPQKPIPRPLNKFQG 1467
             N  +  GSK   + +   L+   G
Sbjct: 697  -NRRRSAGSKSRSQRVDTLLHHMLG 720


