query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 71/280 (25%), Positives = 125/280 (44%), Gaps = 36/280 (12%)

Query: 1363 VTSQIFDIIIISLIILNMISMMAES---YNQPKAMKSILDHLNWVFVVIFTLECLIKIFA 1419
            V S  F   I  ++I+N I+++ E+     +  A K       +VF  I+ LE  +KI+ 
Sbjct: 427  VRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKP-WQVAEFVFGWIYVLEMALKIYT 485

Query: 1420 LRQYYFTNGW----NLFDCVVVLLSIVSTMISTLENQEHIPFPP-TLFRIVRLARIGRIL 1474
               Y F N W    N FD +V  + ++    + +   E+  F      R + LAR+ R++
Sbjct: 486  ---YGFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLI 542

Query: 1475 RLVRAARGIRTLLFALMMSLPSLFNIGLLLFLIMFIYAILGMNWFSKV---------NPE 1525
            RL+   +  R  +   +  +PSL      +F ++ IY  +G+  F  +           E
Sbjct: 543  RLLMNVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETE 602

Query: 1526 SGIDD--IFNFKTFASSMLCLFQISTSAGWDSLLSPMLRSKESCNSSSENCHLPGIATSY 1583
               DD  +FNF  + + M+ LF +     W   +            S ++      + +Y
Sbjct: 603  LAEDDYLLFNFNDYPNGMVTLFNLLVMGNWQVWME-----------SYKDLTGTWWSITY 651

Query: 1584 FVSYIIISFLIVVNMYIAVILENFNTA--TEESEDPLGED 1621
            FVS+ +I+ L+++N+ +A +LE F T    EE E   G+D
Sbjct: 652  FVSFYVITILLLLNLVVAFVLEAFFTELDLEEEEKCQGQD 691



 Score = 56.6 bits (135), Expect = 2e-07,   Method: Composition-based stats.
 Identities = 65/264 (24%), Positives = 115/264 (43%), Gaps = 24/264 (9%)

Query: 570 LRTVMTDPFTELAITICIIINTVFLAMEH--HKMEASFEKMLNIGNLVFTSIFIAEMCLK 627
           LR  +  P    AI+  +IIN + + +E      E+S +K   +   VF  I++ EM LK
Sbjct: 423 LRAFVRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALK 482

Query: 628 IIALDPYHYFRRGWNIFDSIVA-LLSFADVM-------NCVLQKRSW-PFLRSFRVLRVF 678
           I      +Y+R G N FD +V  ++   +         N       W  +L   R+LR+ 
Sbjct: 483 IYTYGFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLI 542

Query: 679 KL----AKSWPTLNTLIKIIGNSVGALGSLTVVLVIVIFIFSVVGMQLFGRSFNSQKSPK 734
           +L     +    + T I +I + +  LG++  VL     I+  +G+Q+FG   N+     
Sbjct: 543 RLLMNVQRYRAFIATFITLIPSLMPYLGTIFCVLC----IYCSIGVQVFGGLVNAGNKKL 598

Query: 735 LCNPTGPTVSCLRHWHMGDFWHSFLVVFRILC-GEWIENMWECMQEANASSSLCVIVFIL 793
                      L  ++  D+ +  + +F +L  G W   +W    +    +   +  F+ 
Sbjct: 599 FETELAEDDYLL--FNFNDYPNGMVTLFNLLVMGNW--QVWMESYKDLTGTWWSITYFVS 654

Query: 794 ITVIGKLVVLNLFIALLLNSFSNE 817
             VI  L++LNL +A +L +F  E
Sbjct: 655 FYVITILLLLNLVVAFVLEAFFTE 678



 Score = 55.4 bits (132), Expect = 3e-07,   Method: Composition-based stats.
 Identities = 64/308 (20%), Positives = 116/308 (37%), Gaps = 47/308 (15%)

Query: 1053 VKHSWFESFIIFVILLSSGALIFEDVHLENQPKIQELLNCTDIIFTHIFILEMVLKWVAF 1112
            V+   F   I F+++++  A++ E      +   Q+     + +F  I++LEM LK   +
Sbjct: 427  VRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTY 486

Query: 1113 GFGKYFTSAWCCLDF----IIVIVSVTTLINLME---------LKSFRTLRALRPLRALS 1159
            GF  Y+       DF    +IVI    T I   E         ++     R LR +R L 
Sbjct: 487  GFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLM 546

Query: 1160 QFEGMKVVVNALIGAIPAILNVLLVCLIFWLVFCILGVYFFSGKFGKCINGTDSVINYTI 1219
              +  +  +   I  IP+++  L        ++C +GV  F G     +N  +  +  T 
Sbjct: 547  NVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGG----LVNAGNKKLFETE 602

Query: 1220 ITNKSQCESGNFSWINQKVNFDNVGNAYLALLQVATFKGWMDIIYAAVDSTEKEQQPEFE 1279
            +                  NF++  N  + L  +     W             E   +  
Sbjct: 603  LAEDDYL----------LFNFNDYPNGMVTLFNLLVMGNW---------QVWMESYKDLT 643

Query: 1280 SNSLGYIYFVVFIIFGSFFTLNLFIGVIIDNFN-----QQQKKLGGQDIFMTEEQKKYYN 1334
                   YFV F +      LNL +  +++ F      ++++K  GQD   ++E++   N
Sbjct: 644  GTWWSITYFVSFYVITILLLLNLVVAFVLEAFFTELDLEEEEKCQGQD---SQEKR---N 697

Query: 1335 AMKKLGSK 1342
              +  GSK
Sbjct: 698  RRRSAGSK 705



 Score = 47.7 bits (112), Expect = 8e-05,   Method: Composition-based stats.
 Identities = 39/200 (19%), Positives = 81/200 (40%), Gaps = 28/200 (14%)

Query: 1418 FALRQYYFTNGWNLFDCVVVLLSIVSTMISTLENQEHIPFPPTLFRIV--RLARIGRILR 1475
            +   + ++T+  NL     V++  V  ++  L         P  F  +  R+A   R++ 
Sbjct: 141  YEGSRIFWTSRLNLVKVACVVILFVDVLVDFL------YLSPLAFDFLPFRIAPYVRVII 194

Query: 1476 LVRAARGIRTLLFALMMSLPSLFNIGLLLFLIMFIYAILGMNWFSKVNPESGIDDIFNFK 1535
             + + R +R  L  L   L +  NI  L  L +     L  +W + V  E     +  F 
Sbjct: 195  FILSIRELRDTLVLLSGMLGTYLNILALWMLFL-----LFASWIAFVMFEDTQQGLTVFT 249

Query: 1536 TFASSMLCLFQI-STSAGWDSLLSPMLRSKESCNSSSENCHLPGIATSYFVSYIIISFLI 1594
            ++ +++  +F + +TS   D  +     S+               ++ +FV Y++I    
Sbjct: 250  SYGATLYQMFILFTTSNNPDVWIPAYKSSR--------------WSSVFFVLYVLIGVYF 295

Query: 1595 VVNMYIAVILENFNTATEES 1614
            V N+ +AV+ ++F     + 
Sbjct: 296  VTNLILAVVYDSFKEQLAKQ 315



 Score = 45.4 bits (106), Expect = 3e-04,   Method: Composition-based stats.
 Identities = 29/98 (29%), Positives = 52/98 (53%), Gaps = 10/98 (10%)

Query: 340 TNFDNFGWSFLAMFRLMTQ----DSWEKLYQQTLRTTGLYSVFFFIVVIFLGSFYLINLT 395
           T F ++G +   MF L T     D W   Y+ +      +S  FF++ + +G +++ NL 
Sbjct: 246 TVFTSYGATLYQMFILFTTSNNPDVWIPAYKSSR-----WSSVFFVLYVLIGVYFVTNLI 300

Query: 396 LAVVTMAYEEQ-NKNVAAEIEAKEKMFQEAQQLLKEEK 432
           LAVV  +++EQ  K V+   + K +M ++A  L+  +K
Sbjct: 301 LAVVYDSFKEQLAKQVSGMDQMKRRMLEKAFGLIDSDK 338


