query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 92/440 (20%), Positives = 176/440 (40%), Gaps = 107/440 (24%)

Query: 1425 MDIMYAAVDSRNVELQPKYEDNLYMYLYFVIFIIFGSFFTLNLFIGVIIDNF-------- 1476
            M I++   ++ +V + P Y+ + +  ++FV++++ G +F  NL + V+ D+F        
Sbjct: 258  MFILFTTSNNPDVWI-PAYKSSRWSSVFFVLYVLIGVYFVTNLILAVVYDSFKEQLAKQV 316

Query: 1477 ---NQQKKK-----FGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPANKFQGMVFD-- 1526
               +Q K++     FG  D     E  K    +K        + +P+ + +  G++FD  
Sbjct: 317  SGMDQMKRRMLEKAFGLIDSDKNGEIDKN-QCIKLFEQLTNYRTLPKISKEEFGLIFDEL 375

Query: 1527 --------------------------------------------------FVTKQVFDIS 1536
                                                              FV    F  +
Sbjct: 376  DDTRDFKINKDEFADLCQAIALRFQKEEVPSLFEHFPQIYHSALSQQLRAFVRSPNFGYA 435

Query: 1537 IMILICLNMVTMMVETDDQSQEMTNILYW--INLVFIVLFTGECVLKLISLRYY-YFTIG 1593
            I  ++ +N + ++VET    +E +    W     VF  ++  E  LK+ +  +  Y+  G
Sbjct: 436  ISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTYGFENYWREG 495

Query: 1594 WNIFDFVVVILSIVG---MFLAELIEKYFVSPTLFRVIRLARIGRILRLIKGAKGIRTLL 1650
             N FDF+V  + ++G    F+      +F +    R + LAR+ R++RL+   +  R  +
Sbjct: 496  ANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNVQRYRAFI 555

Query: 1651 FALMMSLPALFNIGLLLFLVMFIYAIFGMSNFA---------YVKREVGIDD--MFNFET 1699
               +  +P+L      +F V+ IY   G+  F            + E+  DD  +FNF  
Sbjct: 556  ATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETELAEDDYLLFNFND 615

Query: 1700 FGNSMICLFQITTSAGWDGLLAPILNSGPPDCDPDKDHPGSSVKGDCGNPSVGIFFFVSY 1759
            + N M+ LF +     W   +           +  KD  G+            I +FVS+
Sbjct: 616  YPNGMVTLFNLLVMGNWQVWM-----------ESYKDLTGT---------WWSITYFVSF 655

Query: 1760 IIISFLVVVNMYIAVILENF 1779
             +I+ L+++N+ +A +LE F
Sbjct: 656  YVITILLLLNLVVAFVLEAF 675



 Score = 74.3 bits (181), Expect = 8e-13,   Method: Composition-based stats.
 Identities = 60/273 (21%), Positives = 109/273 (39%), Gaps = 35/273 (12%)

Query: 1210 FETFIVFMILLSSGALAFEDIYIEQRKTIKTMLEYADKVFTYIFILEMLLKWVAYGFQVY 1269
            F   I F+++++  A+  E     +  + +   + A+ VF +I++LEM LK   YGF+ Y
Sbjct: 432  FGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTYGFENY 491

Query: 1270 FTNAWCWLDFLIVDVSLVSLTANALG------YSELGAIKSLRTLRALRPLRALSRFEGM 1323
            +       DFL+  V ++  TA  +       +S    I+ L   R LR +R L   +  
Sbjct: 492  WREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNVQRY 551

Query: 1324 RVVVNALLGAIPSIMNVLLVCLIFWLIFSIMGVNLFAGKFYHCINYTTGEMFDVSVVNNY 1383
            R  +   +  IPS+M  L        I+  +GV +F G     +N    ++F+  +  + 
Sbjct: 552  RAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGG----LVNAGNKKLFETELAED- 606

Query: 1384 SECKALIESNQTARWKNVKVNFDNVGLGYLSLLQVATFKGWMDIMYAAVDSRNVELQPKY 1443
                             +  NF++   G ++L  +     W   M +  D          
Sbjct: 607  ---------------DYLLFNFNDYPNGMVTLFNLLVMGNWQVWMESYKDLTGTW----- 646

Query: 1444 EDNLYMYLYFVIFIIFGSFFTLNLFIGVIIDNF 1476
                +   YFV F +      LNL +  +++ F
Sbjct: 647  ----WSITYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 51.6 bits (122), Expect = 5e-06,   Method: Composition-based stats.
 Identities = 64/258 (24%), Positives = 118/258 (45%), Gaps = 30/258 (11%)

Query: 756 VMDPFVDLAITICIVLNTLFMAMEHYPMTEQFSSV--LSVGNLVFTGIFTAEMFLKIIAM 813
           V  P    AI+  +++N + + +E     E+ S+     V   VF  I+  EM LKI   
Sbjct: 427 VRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTY 486

Query: 814 DPYYYFQEGWNIFDGFIVSLSLM------------ELGLANVEGLSVLRSFRLLRVFKL- 860
               Y++EG N FD F+V+  ++                +N E +  L   R+LR+ +L 
Sbjct: 487 GFENYWREGANRFD-FLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLL 545

Query: 861 ---AKSWPTLNMLIKIIGNSVGALGNLTLVLAIIVFIFAVVGMQLFGK-----SYKECVC 912
               +    +   I +I + +  LG +  VL I    +  +G+Q+FG      + K    
Sbjct: 546 MNVQRYRAFIATFITLIPSLMPYLGTIFCVLCI----YCSIGVQVFGGLVNAGNKKLFET 601

Query: 913 KISNDCELPRWHMHDFFHSFLIVFRVLC-GEWIETMWDCMEVAGQTMCLTVFMMVMVIGN 971
           +++ D  L  ++ +D+ +  + +F +L  G W   M    ++ G    +T F+   VI  
Sbjct: 602 ELAEDDYL-LFNFNDYPNGMVTLFNLLVMGNWQVWMESYKDLTGTWWSITYFVSFYVITI 660

Query: 972 LVVLNLFLALLLSSFSSD 989
           L++LNL +A +L +F ++
Sbjct: 661 LLLLNLVVAFVLEAFFTE 678



 Score = 48.5 bits (114), Expect = 5e-05,   Method: Composition-based stats.
 Identities = 46/230 (20%), Positives = 90/230 (39%), Gaps = 31/230 (13%)

Query: 1582 LISLRYYYFTIGWNIFDFVVVILSIVGMFLAELIEKYFVSPTLFRVI--RLARIGRILRL 1639
               + Y    I W     +V +  +V +F+  L++  ++SP  F  +  R+A   R++  
Sbjct: 136  FFPISYEGSRIFWTSRLNLVKVACVVILFVDVLVDFLYLSPLAFDFLPFRIAPYVRVIIF 195

Query: 1640 IKGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKREVGIDDMFNFET 1699
            I   + +R  L  L   L    NI   L+++  ++A +     A+V  E     +  F +
Sbjct: 196  ILSIRELRDTLVLLSGMLGTYLNILA-LWMLFLLFASW----IAFVMFEDTQQGLTVFTS 250

Query: 1700 FGNSMICLFQI-TTSAGWDGLLAPILNSGPPDCDPDKDHPGSSVKGDCGNPSVGIFFFVS 1758
            +G ++  +F + TTS   D  +    +S                            FFV 
Sbjct: 251  YGATLYQMFILFTTSNNPDVWIPAYKSSR-----------------------WSSVFFVL 287

Query: 1759 YIIISFLVVVNMYIAVILENFSVATEESAEPLSEDDFEMFYEVWEKFDPD 1808
            Y++I    V N+ +AV+ ++F     +    + +    M  + +   D D
Sbjct: 288  YVLIGVYFVTNLILAVVYDSFKEQLAKQVSGMDQMKRRMLEKAFGLIDSD 337


