query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 65/270 (24%), Positives = 115/270 (42%), Gaps = 37/270 (13%)

Query: 1537 FVTRQVFDISIMILICLNMVTMMVET--DDQSEYVTTILSRINLVFIVLFTGECVLKLIS 1594
            FV    F  +I  ++ +N + ++VET  D +             VF  ++  E  LK+ +
Sbjct: 426  FVRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYT 485

Query: 1595 LR-HYYFTIGWNIFDFVVVILSIVG---MFLAELIEKYFVSPTLFRVIRLARIGRILRLI 1650
                 Y+  G N FDF+V  + ++G    F+      +F +    R + LAR+ R++RL+
Sbjct: 486  YGFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLL 545

Query: 1651 KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFA---------YVKREVGI 1701
               +  R  +   +  +P+L      +F V+ IY   G+  F            + E+  
Sbjct: 546  MNVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETELAE 605

Query: 1702 DD--MFNFETFGNSMICLFQITTSAGWDGLLAPILNSKPPDCDPNKVNPGSSVKGDCGNP 1759
            DD  +FNF  + N M+ LF +     W   +                    S K D    
Sbjct: 606  DDYLLFNFNDYPNGMVTLFNLLVMGNWQVWM-------------------ESYK-DLTGT 645

Query: 1760 SVGIFFFVSYIIISFLVVVNMYIAVILENF 1789
               I +FVS+ +I+ L+++N+ +A +LE F
Sbjct: 646  WWSITYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 66.2 bits (160), Expect = 3e-10,   Method: Composition-based stats.
 Identities = 72/309 (23%), Positives = 128/309 (41%), Gaps = 46/309 (14%)

Query: 1220 FETFIVFMILLSSGALAFEDIYIDQRKTIKTMLEYADKVFTYIFILEMLLKWVAYGYQTY 1279
            F   I F+++++  A+  E     +  + +   + A+ VF +I++LEM LK   YG++ Y
Sbjct: 432  FGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTYGFENY 491

Query: 1280 FTNAWCWLDFLIVDVSLVSLTANALG------YSELGAIKSLRTLRALRPLRALSRFEGM 1333
            +       DFL+  V ++  TA  +       +S    I+ L   R LR +R L   +  
Sbjct: 492  WREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNVQRY 551

Query: 1334 RVVVNALLGAIPSIMNVLLVCLIFWLIFSIMGVNLFAGKFYHCINTTTGDRFDIEDVNNH 1393
            R  +   +  IPS+M  L        I+  +GV +F G          G++         
Sbjct: 552  RAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGL------VNAGNK--------- 596

Query: 1394 TDCLKLIERNETARWKNVKVNFDNVGFGYLSLLQVATFKGWMDIMYAAVDSRNVELQPKY 1453
                KL E  E A    +  NF++   G ++L  +     W   M +  D          
Sbjct: 597  ----KLFE-TELAEDDYLLFNFNDYPNGMVTLFNLLVMGNWQVWMESYKDLTG------- 644

Query: 1454 EESLYMYLYFVIFIIFGSFFTLNLFIGVIIDNFN-----QQKKKFGGQDIFMTEEQKKYY 1508
              + +   YFV F +      LNL +  +++ F      ++++K  GQD   ++E++   
Sbjct: 645  --TWWSITYFVSFYVITILLLLNLVVAFVLEAFFTELDLEEEEKCQGQD---SQEKR--- 696

Query: 1509 NAMKKLGSK 1517
            N  +  GSK
Sbjct: 697  NRRRSAGSK 705



 Score = 53.1 bits (126), Expect = 2e-06,   Method: Composition-based stats.
 Identities = 60/216 (27%), Positives = 99/216 (45%), Gaps = 28/216 (12%)

Query: 802 VGNLVFTGIFTAEMFLKIIAMDPYYYFQEGWNIFDGFIVTLSLV------------ELGL 849
           V   VF  I+  EM LKI       Y++EG N FD F+VT  +V                
Sbjct: 466 VAEFVFGWIYVLEMALKIYTYGFENYWREGANRFD-FLVTWVIVIGETATFITPDENTFF 524

Query: 850 ANVEGLSVLRSFRLLRVFKL----AKSWPTLNMLIKIIGNSVGALGNLTLVLAIIVFIFA 905
           +N E +  L   R+LR+ +L     +    +   I +I + +  LG +  VL     I+ 
Sbjct: 525 SNGEWIRYLLLARMLRLIRLLMNVQRYRAFIATFITLIPSLMPYLGTIFCVLC----IYC 580

Query: 906 VVGMQLFG-----KSYKDCVCKIASDCQLPRWHMNDFFHSFLIVFRVLC-GEWIETMWDC 959
            +G+Q+FG      + K    ++A D  L  ++ ND+ +  + +F +L  G W   M   
Sbjct: 581 SIGVQVFGGLVNAGNKKLFETELAEDDYL-LFNFNDYPNGMVTLFNLLVMGNWQVWMESY 639

Query: 960 MEVAGQAMCLTVFMMVMVIGNLVVLNLFLALLLSSF 995
            ++ G    +T F+   VI  L++LNL +A +L +F
Sbjct: 640 KDLTGTWWSITYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 48.1 bits (113), Expect = 7e-05,   Method: Composition-based stats.
 Identities = 48/243 (19%), Positives = 99/243 (40%), Gaps = 42/243 (17%)

Query: 1599 YFTIGWNIFDFVVVILSIVGMFLAELIEKYFVSPTLFRVI--RLARIGRILRLIKGAKGI 1656
            ++T   N    +V +  +V +F+  L++  ++SP  F  +  R+A   R++  I   + +
Sbjct: 147  FWTSRLN----LVKVACVVILFVDVLVDFLYLSPLAFDFLPFRIAPYVRVIIFILSIREL 202

Query: 1657 RTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKREVGIDDMFNFETFGNSMIC 1716
            R  L  L   L    NI   L+++  ++A +     A+V  E     +  F ++G ++  
Sbjct: 203  RDTLVLLSGMLGTYLNILA-LWMLFLLFASW----IAFVMFEDTQQGLTVFTSYGATLYQ 257

Query: 1717 LFQI-TTSAGWDGLLAPILNSKPPDCDPNKVNPGSSVKGDCGNPSVGIFFFVSYIIISFL 1775
            +F + TTS   D  +    +S+                           FFV Y++I   
Sbjct: 258  MFILFTTSNNPDVWIPAYKSSR-----------------------WSSVFFVLYVLIGVY 294

Query: 1776 VVVNMYIAVILENFSVATEESAEPLSEDDFEMFYEVWEKFDPDATQFME-------FEKL 1828
             V N+ +AV+ ++F     +    + +    M  + +   D D    ++       FE+L
Sbjct: 295  FVTNLILAVVYDSFKEQLAKQVSGMDQMKRRMLEKAFGLIDSDKNGEIDKNQCIKLFEQL 354

Query: 1829 SQF 1831
            + +
Sbjct: 355  TNY 357


