query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 65/270 (24%), Positives = 114/270 (42%), Gaps = 37/270 (13%)

Query: 1522 FVTRQVFDISIMILICLNMVTMMVET--DDQGKYMTLVLSRINLVFIVLFTGEFVLKLVS 1579
            FV    F  +I  ++ +N + ++VET  D +             VF  ++  E  LK+ +
Sbjct: 426  FVRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYT 485

Query: 1580 LR-HYYFTIGWNIFDFVVVILSIVG---MFLAEMIEKYFVSPTLFRVIRLARIGRILRLI 1635
                 Y+  G N FDF+V  + ++G    F+      +F +    R + LAR+ R++RL+
Sbjct: 486  YGFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLL 545

Query: 1636 KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFA---------YVKKEAGI 1686
               +  R  +   +  +P+L      +F V+ IY   G+  F            + E   
Sbjct: 546  MNVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETELAE 605

Query: 1687 DD--MFNFETFGNSMICLFQITTSAGWDGLLAPILNSAPPDCDPDTIHPGSSVKGDCGNP 1744
            DD  +FNF  + N M+ LF +     W   +                    S K D    
Sbjct: 606  DDYLLFNFNDYPNGMVTLFNLLVMGNWQVWM-------------------ESYK-DLTGT 645

Query: 1745 SVGIFFFVSYIIISFLVVVNMYIAVILENF 1774
               I +FVS+ +I+ L+++N+ +A +LE F
Sbjct: 646  WWSITYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 66.2 bits (160), Expect = 2e-10,   Method: Composition-based stats.
 Identities = 70/306 (22%), Positives = 124/306 (40%), Gaps = 43/306 (14%)

Query: 1208 FETFIVFMILLSSGALAFEDIYIEQRKTIKTMLEYADKVFTYIFILEMLLKWVAYGFQTY 1267
            F   I F+++++  A+  E     +  + +   + A+ VF +I++LEM LK   YGF+ Y
Sbjct: 432  FGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTYGFENY 491

Query: 1268 FTNAWCWLDFLIVDVSLVSLVANALG------YSELGAIKSLRTLRALRPLRALSRFEGM 1321
            +       DFL+  V ++   A  +       +S    I+ L   R LR +R L   +  
Sbjct: 492  WREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLMNVQRY 551

Query: 1322 RVVVNALVGAIPSIMNVLLVCLIFWLIFSIMGVNLFAGKFYHCVNMTTGNMFDISDVNNL 1381
            R  +   +  IPS+M  L        I+  +GV +F G     VN     +F+       
Sbjct: 552  RAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGG----LVNAGNKKLFET------ 601

Query: 1382 SDCQALGKQARWKNVKVNFDNVGAGYLALLQVATFKGWMDIMYAAVDSRDVKLQPVYEEN 1441
                   + A    +  NF++   G + L  +     W   M +  D             
Sbjct: 602  -------ELAEDDYLLFNFNDYPNGMVTLFNLLVMGNWQVWMESYKD---------LTGT 645

Query: 1442 LYMYLYFVIFIIFGSFFTLNLFIGVIIDNFN-----QQKKKFGGQDIFMTEEQKKYYNAM 1496
             +   YFV F +      LNL +  +++ F      ++++K  GQD   ++E++   N  
Sbjct: 646  WWSITYFVSFYVITILLLLNLVVAFVLEAFFTELDLEEEEKCQGQD---SQEKR---NRR 699

Query: 1497 KKLGSK 1502
            +  GSK
Sbjct: 700  RSAGSK 705



 Score = 53.5 bits (127), Expect = 1e-06,   Method: Composition-based stats.
 Identities = 64/258 (24%), Positives = 114/258 (44%), Gaps = 30/258 (11%)

Query: 757 VMDPFVDLAITICIVLNTLFMAMEHYPMTEQFSSV--LTVGNLVFTGIFTAEMVLKIIAM 814
           V  P    AI+  +++N + + +E     E+ S+     V   VF  I+  EM LKI   
Sbjct: 427 VRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTY 486

Query: 815 DPYYYFQEGWNIFDGIIVSLSLM-----------ELGLSNVEGLSVLRSFRLLRVFKL-- 861
               Y++EG N FD ++  + ++               SN E +  L   R+LR+ +L  
Sbjct: 487 GFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLM 546

Query: 862 --AKSWPTLNMLIKIIGNSVGALGNLTLVLAIIVFIFAVVGMQLFGKSYKECVCKI---- 915
              +    +   I +I + +  LG +  VL     I+  +G+Q+FG        K+    
Sbjct: 547 NVQRYRAFIATFITLIPSLMPYLGTIFCVLC----IYCSIGVQVFGGLVNAGNKKLFETE 602

Query: 916 --NDDCTLPRWHMNDFFHSFLIVFRVLC-GEWIETMWDCMEVAGQTMCLIVFMLVMVIGN 972
              DD  L  ++ ND+ +  + +F +L  G W   M    ++ G    +  F+   VI  
Sbjct: 603 LAEDDYLL--FNFNDYPNGMVTLFNLLVMGNWQVWMESYKDLTGTWWSITYFVSFYVITI 660

Query: 973 LVVLNLFLALLLSSFSSD 990
           L++LNL +A +L +F ++
Sbjct: 661 LLLLNLVVAFVLEAFFTE 678



 Score = 47.0 bits (110), Expect = 1e-04,   Method: Composition-based stats.
 Identities = 44/223 (19%), Positives = 90/223 (40%), Gaps = 35/223 (15%)

Query: 1584 YFTIGWNIFDFVVVILSIVGMFLAEMIEKYFVSPTLFRVI--RLARIGRILRLIKGAKGI 1641
            ++T   N    +V +  +V +F+  +++  ++SP  F  +  R+A   R++  I   + +
Sbjct: 147  FWTSRLN----LVKVACVVILFVDVLVDFLYLSPLAFDFLPFRIAPYVRVIIFILSIREL 202

Query: 1642 RTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKKEAGIDDMFNFETFGNSMIC 1701
            R  L  L   L    NI   L+++  ++A +     A+V  E     +  F ++G ++  
Sbjct: 203  RDTLVLLSGMLGTYLNILA-LWMLFLLFASW----IAFVMFEDTQQGLTVFTSYGATLYQ 257

Query: 1702 LFQI-TTSAGWDGLLAPILNSAPPDCDPDTIHPGSSVKGDCGNPSVGIFFFVSYIIISFL 1760
            +F + TTS   D  +    +S                            FFV Y++I   
Sbjct: 258  MFILFTTSNNPDVWIPAYKSSR-----------------------WSSVFFVLYVLIGVY 294

Query: 1761 VVVNMYIAVILENFSVATEESAEPLSEDDFEMFYEVWEKFDPD 1803
             V N+ +AV+ ++F     +    + +    M  + +   D D
Sbjct: 295  FVTNLILAVVYDSFKEQLAKQVSGMDQMKRRMLEKAFGLIDSD 337


