query
>KCNS3_HUMAN#plasma membrane#Golgi apparatus GO:0005794(IDA); plasma
 Identities = 44/166 (26%), Positives = 80/166 (48%), Gaps = 22/166 (13%)

Query: 1537 LICLNMVTMMV------ETDDQSPEKINILAKINLLFVAIFTGECIVKLAAL--RHYYFT 1588
            ++  ++V M V      + +D   +   +L  + +  +A FTGE  V+LAA   +  ++ 
Sbjct: 194  VVLASIVAMCVHSMSEFQNEDGEVDDP-VLEGVEIACIAWFTGELAVRLAAAPCQKKFWK 252

Query: 1589 NSWNIFDFVVVILSIVGTVLSDIIQKYFFS----PTLFRVIRLARIGRILRLIRGAKGIR 1644
            N  NI DF V I+    T+  D  ++          + +++RL RI RIL+L R + G+R
Sbjct: 253  NPLNIIDF-VSIIPFYATLAVDTKEEESEDIENMGKVVQILRLMRIFRILKLARHSVGLR 311

Query: 1645 TLLFALMMSLPALFNIGLLLFLVMFIYSIFGMANFAYVKWEAGIDD 1690
            +L   L     +   +GLLL     ++   G++ F+ + +    DD
Sbjct: 312  SLGATLRH---SYHEVGLLL-----LFLSVGISIFSVLIYSVEKDD 349


