query
>TPC1_ARATH#vacuole membrane#Golgi apparatus GO:0005794(IDA); integral
 Identities = 64/273 (23%), Positives = 116/273 (42%), Gaps = 43/273 (15%)

Query: 1511 LVTNQAFDISIMVLICLNMVTMMVE-----KEGQSQHMTEVLYWINVVFIILFTGECVLK 1565
             V +  F  +I  ++ +N + ++VE     +E  +Q   +V      VF  ++  E  LK
Sbjct: 426  FVRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQV---AEFVFGWIYVLEMALK 482

Query: 1566 LISLR-HYYFTVGWNIFDFVVVIISIVG---MFLADLIETYFVSPTLFRVIRLARIGRIL 1621
            + +     Y+  G N FDF+V  + ++G    F+     T+F +    R + LAR+ R++
Sbjct: 483  IYTYGFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLI 542

Query: 1622 RLVKGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFA---------YVKKE 1672
            RL+   +  R  +   +  +P+L      +F V+ IY   G+  F            + E
Sbjct: 543  RLLMNVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIGVQVFGGLVNAGNKKLFETE 602

Query: 1673 DGIND--MFNFETFGNSMICLFQITTSAGWDGLLAPILNSKPPDCDPKKVHPGSSVEGDC 1730
               +D  +FNF  + N M+ LF +     W   +                        D 
Sbjct: 603  LAEDDYLLFNFNDYPNGMVTLFNLLVMGNWQVWMESY--------------------KDL 642

Query: 1731 GNPSVGIFYFVSYIIISFLVVVNMYIAVILENF 1763
                  I YFVS+ +I+ L+++N+ +A +LE F
Sbjct: 643  TGTWWSITYFVSFYVITILLLLNLVVAFVLEAF 675



 Score = 64.7 bits (156), Expect = 6e-10,   Method: Composition-based stats.
 Identities = 65/277 (23%), Positives = 113/277 (40%), Gaps = 48/277 (17%)

Query: 1227 EYADKIFTYIFILEMLLKWIAYGYKTYFTNAWCWLDFLIVDV-------SLVTLVANTLG 1279
            + A+ +F +I++LEM LK   YG++ Y+       DFL+  V       + +T   NT  
Sbjct: 465  QVAEFVFGWIYVLEMALKIYTYGFENYWREGANRFDFLVTWVIVIGETATFITPDENTF- 523

Query: 1280 YSDLGPIKSLRTLRALRPLRALSRFEGMRVVVNALIGAIPSIMNVLLVCLIFWLIFSIMG 1339
            +S+   I+ L   R LR +R L   +  R  +   I  IPS+M  L        I+  +G
Sbjct: 524  FSNGEWIRYLLLARMLRLIRLLMNVQRYRAFIATFITLIPSLMPYLGTIFCVLCIYCSIG 583

Query: 1340 VNLFAGKFYECINTTDGSRFPASQVPNRSECFALMNVSQNVRWKNLKVNFDNVGLGYLSL 1399
            V +F G     +N  +   F      +    F                NF++   G ++L
Sbjct: 584  VQVFGG----LVNAGNKKLFETELAEDDYLLF----------------NFNDYPNGMVTL 623

Query: 1400 LQVATFKGWTIIMYAAVDSVNVDKQPKYEYSLYMYIYFVVFIIFGSFFTLNLFIGVIIDN 1459
              +     W + M +  D            + +   YFV F +      LNL +  +++ 
Sbjct: 624  FNLLVMGNWQVWMESYKDLTG---------TWWSITYFVSFYVITILLLLNLVVAFVLEA 674

Query: 1460 FN-----QQKKKLGGQDIFMTEEQKKYYNAMKKLGSK 1491
            F      ++++K  GQD   ++E++   N  +  GSK
Sbjct: 675  FFTELDLEEEEKCQGQD---SQEKR---NRRRSAGSK 705



 Score = 52.3 bits (124), Expect = 3e-06,   Method: Composition-based stats.
 Identities = 44/223 (19%), Positives = 92/223 (41%), Gaps = 35/223 (15%)

Query: 1573 YFTVGWNIFDFVVVIISIVGMFLADLIETYFVSPTLFRVI--RLARIGRILRLVKGAKGI 1630
            ++T   N    +V +  +V +F+  L++  ++SP  F  +  R+A   R++  +   + +
Sbjct: 147  FWTSRLN----LVKVACVVILFVDVLVDFLYLSPLAFDFLPFRIAPYVRVIIFILSIREL 202

Query: 1631 RTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKKEDGINDMFNFETFGNSMIC 1690
            R  L  L   L    NI   L+++  ++A +     A+V  ED    +  F ++G ++  
Sbjct: 203  RDTLVLLSGMLGTYLNILA-LWMLFLLFASW----IAFVMFEDTQQGLTVFTSYGATLYQ 257

Query: 1691 LFQI-TTSAGWDGLLAPILNSKPPDCDPKKVHPGSSVEGDCGNPSVGIFYFVSYIIISFL 1749
            +F + TTS   D  +    +S+                           +FV Y++I   
Sbjct: 258  MFILFTTSNNPDVWIPAYKSSR-----------------------WSSVFFVLYVLIGVY 294

Query: 1750 VVVNMYIAVILENFSVATEESTEPLSEDDFEMFYEVWEKFDPD 1792
             V N+ +AV+ ++F     +    + +    M  + +   D D
Sbjct: 295  FVTNLILAVVYDSFKEQLAKQVSGMDQMKRRMLEKAFGLIDSD 337



 Score = 51.2 bits (121), Expect = 7e-06,   Method: Composition-based stats.
 Identities = 60/258 (23%), Positives = 113/258 (43%), Gaps = 30/258 (11%)

Query: 741 VMDPFVDLAITICIVLNTLFMAMEHHPMTEE--FKNVLAIGNLVFTGIFAAEMVLKLIAM 798
           V  P    AI+  +++N + + +E     EE   +    +   VF  I+  EM LK+   
Sbjct: 427 VRSPNFGYAISFILIINFIAVVVETTLDIEESSAQKPWQVAEFVFGWIYVLEMALKIYTY 486

Query: 799 DPYEYFQVGWNIFDSLIVTLSLV-----------ELFLADVEGLSVLRSFRLLRVFKL-- 845
               Y++ G N FD L+  + ++             F ++ E +  L   R+LR+ +L  
Sbjct: 487 GFENYWREGANRFDFLVTWVIVIGETATFITPDENTFFSNGEWIRYLLLARMLRLIRLLM 546

Query: 846 --AKSWPTLNMLIKIIGNSVGALGNLTLVLAIIVFIFAVVGMQLFGKSYKECVCKI---- 899
              +    +   I +I + +  LG +  VL     I+  +G+Q+FG        K+    
Sbjct: 547 NVQRYRAFIATFITLIPSLMPYLGTIFCVLC----IYCSIGVQVFGGLVNAGNKKLFETE 602

Query: 900 --NDDCTLPRWHMNDFFHSFLIVFRVLC-GEWIETMWDCMEVAGQAMCLIVYMMVMVIGN 956
              DD  L  ++ ND+ +  + +F +L  G W   M    ++ G    +  ++   VI  
Sbjct: 603 LAEDDYLL--FNFNDYPNGMVTLFNLLVMGNWQVWMESYKDLTGTWWSITYFVSFYVITI 660

Query: 957 LVVLNLFLALLLSSFSSD 974
           L++LNL +A +L +F ++
Sbjct: 661 LLLLNLVVAFVLEAFFTE 678


